forci_menu_builder_menu_list:
    path:       /list
    controller: Forci\Bundle\MenuBuilder\Controller\MenuController:listAction

forci_menu_builder_menu_create:
    path:       /create
    controller: Forci\Bundle\MenuBuilder\Controller\MenuController:createAction

forci_menu_builder_menu_list_row_refresh:
    path:       /{id}/list/refresh
    controller: Forci\Bundle\MenuBuilder\Controller\MenuController:refreshListRowAction

forci_menu_builder_menu_edit:
    path:       /{id}/edit
    controller: Forci\Bundle\MenuBuilder\Controller\MenuController:editAction

forci_menu_builder_menu_name_update:
    path:       /{id}/update/name
    controller: Forci\Bundle\MenuBuilder\Controller\MenuController:updateNameAction

forci_menu_builder_menu_preview:
    path:       /{id}/preview
    controller: Forci\Bundle\MenuBuilder\Controller\MenuController:previewAction

forci_menu_builder_menu_make_system:
    path:       /{id}/make/system
    controller: Forci\Bundle\MenuBuilder\Controller\MenuController:makeSystemAction

forci_menu_builder_menu_make_public:
    path:       /{id}/make/public
    controller: Forci\Bundle\MenuBuilder\Controller\MenuController:makePublicAction
