forci_menu_builder_route_list:
    path:       /list
    controller: Forci\Bundle\MenuBuilder\Controller\RouteController:listRoutesAction

forci_menu_builder_route_refresh_row:
    path:       /{id}/refresh/row
    controller: Forci\Bundle\MenuBuilder\Controller\RouteController:refreshListRowAction

forci_menu_builder_route_name_update:
    path:       /{id}/update/name
    controller: Forci\Bundle\MenuBuilder\Controller\RouteController:updateRouteNameAction

forci_menu_builder_route_parameter_name_update:
    path:       /parameters/{id}/update/name
    controller: Forci\Bundle\MenuBuilder\Controller\RouteController:updateRouteParameterNameAction

forci_menu_builder_route_import:
    path:       /import
    controller: Forci\Bundle\MenuBuilder\Controller\RouteController:importAction

forci_menu_builder_route_make_system:
    path:       /{id}/make/system
    controller: Forci\Bundle\MenuBuilder\Controller\RouteController:makeSystemAction

forci_menu_builder_route_make_public:
    path:       /{id}/make/public
    controller: Forci\Bundle\MenuBuilder\Controller\RouteController:makePublicAction

