forci_menu_builder_dashboard:
    path:        /
    controller: Forci\Bundle\MenuBuilder\Controller\DashboardController:dashboardAction

forci_menu_builder_route:
    resource: routing/route.yml
    prefix: /routes

forci_menu_builder_menu:
    resource: routing/menu.yml
    prefix: /menus